import { Link, createFileRoute, useRouter } from '@tanstack/react-router';
import { useServerFn } from '@tanstack/react-start';
import { useState, type FormEvent } from 'react';
import { createFolder, createUploadIntent, confirmUpload, deleteFile, getDownloadUrl, getFiles, getFolders, moveFile } from '@/features/files/server';
import { currentSession } from '@/server/auth';
import { createServerFn } from '@tanstack/react-start';
import * as styles from '@/styles/app.css';

const getViewer = createServerFn({ method: 'GET' }).handler(() => currentSession());
export const Route = createFileRoute('/files/')({
  loader: async () => {
    const viewer = await getViewer();
    return { viewer, files: viewer ? await getFiles() : [], folders: viewer ? await getFolders() : [] };
  },
  component: FilesPage,
});

function FilesPage() {
  const { viewer, files, folders } = Route.useLoaderData(); const router = useRouter(); const uploadIntent = useServerFn(createUploadIntent); const confirm = useServerFn(confirmUpload); const addFolder = useServerFn(createFolder); const move = useServerFn(moveFile); const remove = useServerFn(deleteFile); const download = useServerFn(getDownloadUrl); const [notice, setNotice] = useState(''); const [folder, setFolder] = useState(''); const [folderParentId, setFolderParentId] = useState('');
  const folderById = new Map(folders.map((item) => [item.id, item]));
  const folderPath = (item: typeof folders[number]): string => { const names = [item.name]; let parentId = item.parentId; const visited = new Set([item.id]); while (parentId && !visited.has(parentId)) { visited.add(parentId); const parent = folderById.get(parentId); if (!parent) break; names.unshift(parent.name); parentId = parent.parentId; } return names.join(' / '); };
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const selected = form.get('file'); if (!(selected instanceof File)) return; if (selected.size > 5 * 1024 * 1024) { setNotice('Files must be 5 MiB or smaller.'); return; }
    const allowed = ['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.oasis.opendocument.text']; if (!allowed.includes(selected.type)) { setNotice('Only PDF, DOCX, and ODT files are allowed.'); return; }
    const tags = String(form.get('tags') ?? '').split(',').map((tag) => tag.trim()).filter(Boolean); const intent = await uploadIntent({ data: { filename: selected.name, mediaType: selected.type as 'application/pdf', sizeBytes: selected.size, folderId: String(form.get('folderId') || '') || null, tagNames: tags } });
    await fetch(intent.uploadUrl, { method: 'PUT', headers: { 'Content-Type': selected.type }, body: selected }); await confirm({ data: { fileId: intent.fileId } }); setNotice('Upload accepted and queued for indexing.'); await router.invalidate(); event.currentTarget.reset(); }
  async function folderSubmit(event: FormEvent) { event.preventDefault(); if (!folder.trim()) return; await addFolder({ data: { name: folder, parentId: folderParentId || null } }); setFolder(''); setFolderParentId(''); await router.invalidate(); }
  async function moveToFolder(fileId: string, targetFolderId: string) { await move({ data: { fileId, folderId: targetFolderId || null } }); setNotice('File moved.'); await router.invalidate(); }
  async function downloadFile(fileId: string) { const { downloadUrl } = await download({ data: { fileId } }); window.location.assign(downloadUrl); }
  async function deleteSelectedFile(fileId: string, filename: string) { if (!window.confirm(`Remove “${filename}” from the library?`)) return; await remove({ data: { fileId } }); setNotice('File removed from the library.'); await router.invalidate(); }
  return <div className={styles.shell}><header className={styles.nav}><Link className={styles.link} to="/">← Docent</Link><span className={styles.muted}>Global file library</span></header><section className={styles.section}>{!viewer && <a className={styles.primaryButton} href="/auth/google">Sign in to browse files</a>}{viewer?.isEditor && <><form className={styles.card} onSubmit={upload}><h2>Upload document</h2><input name="file" type="file" accept=".pdf,.docx,.odt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.oasis.opendocument.text" required /><input name="tags" className={styles.chatInput} placeholder="tags, comma separated" /><select name="folderId"><option value="">No folder</option>{folders.map((item) => <option key={item.id} value={item.id}>{folderPath(item)}</option>)}</select><button className={styles.primaryButton}>Upload</button></form><form className={styles.card} onSubmit={folderSubmit}><h2>Create folder</h2><input className={styles.chatInput} value={folder} onChange={(e) => setFolder(e.target.value)} placeholder="Folder name" /><select value={folderParentId} onChange={(e) => setFolderParentId(e.target.value)}><option value="">Top level</option>{folders.map((item) => <option key={item.id} value={item.id}>{folderPath(item)}</option>)}</select><button className={styles.secondaryButton}>Add folder</button></form></>}{notice && <p className={styles.muted}>{notice}</p>}<div className={styles.grid}>{files.map((file) => <div className={styles.card} key={file.id}><strong>{file.filename}</strong><p className={styles.muted}>{file.mediaType.split('/').pop()} · {(file.sizeBytes / 1024).toFixed(0)} KiB · {file.status}</p><p className={styles.muted}>{file.folderName ?? 'No folder'}{file.tags.length ? ` · ${file.tags.join(', ')}` : ''}</p>{viewer?.isEditor && <p><select defaultValue={file.folderId ?? ''} onChange={(event) => { void moveToFolder(file.id, event.target.value); }}><option value="">No folder</option>{folders.map((item) => <option key={item.id} value={item.id}>{folderPath(item)}</option>)}</select> <button className={styles.secondaryButton} onClick={() => { void downloadFile(file.id); }}>Download</button> <button className={styles.secondaryButton} onClick={() => { void deleteSelectedFile(file.id, file.filename); }}>Remove</button></p>}{!viewer?.isEditor && <button className={styles.secondaryButton} onClick={() => { void downloadFile(file.id); }}>Download</button>}</div>)}</div></section></div>;
}
