import { globalStyle, keyframes, style } from '@vanilla-extract/css';

const thinkingGlow = keyframes({
  '0%, 100%': { transform: 'scale(.92) rotate(-8deg)', opacity: .65, boxShadow: '0 0 0 rgba(31,200,181,0)' },
  '50%': { transform: 'scale(1.08) rotate(8deg)', opacity: 1, boxShadow: '0 0 1.8rem rgba(31,200,181,.42)' },
});
const thinkingDotPulse = keyframes({
  '0%, 60%, 100%': { transform: 'translateY(0)', opacity: .35 },
  '30%': { transform: 'translateY(-.35rem)', opacity: 1 },
});

export const appShell = style({ minHeight: '100vh', background: 'linear-gradient(160deg, #081420, #0c2431)', color: '#eaf3f5' });
export const shell = style({ width: 'min(112rem, calc(100% - 3.2rem))', margin: '0 auto' });
export const nav = style({ height: '7.2rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '0.1rem solid rgba(255,255,255,.1)' });
export const brand = style({ display: 'flex', alignItems: 'center', gap: '1rem', fontSize: '2rem', fontWeight: 700, letterSpacing: '-.03em' });
export const hero = style({ position: 'relative', padding: '8.4rem 0 6rem', overflow: 'hidden', textAlign: 'center' });
export const heroContent = style({ position: 'relative', zIndex: 1 });
export const heroGraph = style({ position: 'absolute', inset: '-4rem 0 auto', height: '56rem', display: 'flex', justifyContent: 'center', pointerEvents: 'none', opacity: .9 });
export const heroGraphSvg = style({ width: '100%', maxWidth: '118rem', height: '100%' });
export const eyebrow = style({ display: 'inline-flex', alignItems: 'center', gap: '0.8rem', marginBottom: '2.6rem', padding: '0.6rem 1.2rem', border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '99.9rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.2rem', letterSpacing: '.08em', textTransform: 'uppercase' });
export const eyebrowDot = style({ width: '0.6rem', height: '0.6rem', borderRadius: '50%', background: '#1fc8b5', boxShadow: '0 0 0.8rem #1fc8b5' });
export const headline = style({ margin: '0 0 1.8rem', fontSize: 'clamp(3.4rem, 5.4vw, 5.8rem)', fontWeight: 600, lineHeight: 1.06, letterSpacing: '-.01em' });
export const gradient = style({ background: 'linear-gradient(100deg, #1fc8b5 10%, #6fa0ff 90%)', WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent' });
export const subhead = style({ maxWidth: '54rem', margin: '0 auto 4.4rem', color: '#9ab1ba', fontSize: '1.7rem', lineHeight: 1.55 });
export const chatBox = style({ maxWidth: '72rem', margin: '0 auto', padding: '1rem', display: 'flex', gap: '1rem', background: '#0f2434', border: '0.1rem solid rgba(117,166,255,.4)', borderRadius: '1.8rem', boxShadow: '0 2rem 6rem rgba(2,10,16,.55)' });
export const homeConsole = style({ position: 'relative', maxWidth: '68rem', margin: '0 auto', padding: '0.8rem', background: '#0f2434', border: '0.1rem solid rgba(255,255,255,.16)', borderRadius: '2.2rem', boxShadow: '0 2rem 6rem rgba(2,10,16,.55)' });
export const homeConsoleRow = style({ display: 'flex', alignItems: 'center', gap: '1rem', padding: '1rem 0.8rem 1rem 1.8rem' });
export const homeConsoleInput = style({ flex: 1, minWidth: '0rem', border: 0, outline: 0, background: 'transparent', color: '#eaf3f5', fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif', fontSize: '1.55rem' });
export const homeSendButton = style({ width: '4rem', height: '4rem', border: 0, borderRadius: '1.2rem', background: 'linear-gradient(135deg, #1fc8b5, #3e7bfa)', color: '#04120f', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 });
export const chatInput = style({ flex: 1, minWidth: '0rem', border: 0, outline: 0, padding: '1.2rem 1.4rem', color: 'inherit', background: 'transparent', fontSize: '1.6rem' });
export const chatPage = style({ height: 'calc(100vh - 7.2rem)' });
export const chatWorkspace = style({ display: 'grid', width: 'min(160rem, calc(100% - 3.2rem))', height: '100%', gridTemplateColumns: '24rem minmax(0, 1fr) 26rem', gap: '2rem', alignItems: 'stretch', minHeight: '0rem', padding: '2.4rem 0', '@media': { 'screen and (max-width: 100rem)': { gridTemplateColumns: '22rem minmax(0, 1fr)' }, 'screen and (max-width: 70rem)': { gridTemplateColumns: '1fr' } } });
export const chatHistory = style({ display: 'flex', flexDirection: 'column', minWidth: '0rem', minHeight: '0rem', overflowY: 'auto', overflowX: 'hidden', padding: '1.6rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.6rem', background: 'rgba(15,36,52,.72)' });
export const chatHistoryHead = style({ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1rem', marginBottom: '1.6rem' });
export const chatKicker = style({ color: '#1fc8b5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1rem', letterSpacing: '.08em', textTransform: 'uppercase' });
export const chatHistoryHeadTitle = style({ margin: '0.4rem 0 0', color: '#eaf3f5', fontSize: '1.9rem' });
export const chatNewButton = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '3.2rem', height: '3.2rem', border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '0.9rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5', cursor: 'pointer' });
export const chatHistorySearch = style({ display: 'flex', alignItems: 'center', gap: '0.8rem', marginBottom: '1.4rem', padding: '0.9rem 1rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '0.9rem', background: '#0c1e2c', color: '#64828c' });
export const chatHistorySearchInput = style({ width: '100%', border: 0, outline: 0, background: 'transparent', color: '#eaf3f5', fontSize: '1.2rem' });
export const chatConversationList = style({ display: 'flex', flexDirection: 'column', gap: '0.4rem', overflowY: 'auto' });
export const chatConversationRow = style({ display: 'flex', alignItems: 'stretch', minWidth: '0rem', borderRadius: '1rem' });
export const chatConversation = style({ display: 'flex', alignItems: 'flex-start', gap: '0.9rem', width: '100%', minWidth: '0rem', padding: '1rem', border: '0.1rem solid transparent', borderRadius: '1rem', background: 'transparent', color: '#64828c', cursor: 'pointer', textAlign: 'left', overflowWrap: 'anywhere' });
export const chatConversationActive = style([chatConversation, { borderColor: 'rgba(31,200,181,.25)', background: 'rgba(31,200,181,.1)', color: '#1fc8b5' }]);
export const chatConversationDelete = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, width: '3.2rem', marginLeft: '0.5rem', border: '0.1rem solid transparent', borderRadius: '0.8rem', background: 'rgba(111,160,255,.08)', color: '#64828c', cursor: 'pointer', opacity: 0 });
export const chatConversationTitle = style({ display: 'block', minWidth: '0rem', color: '#eaf3f5', fontSize: '1.25rem', fontWeight: 500, lineHeight: 1.4, overflowWrap: 'anywhere' });
export const chatConversationMeta = style({ display: 'flex', alignItems: 'center', gap: '0.4rem', marginTop: '0.5rem', color: '#64828c', fontSize: '1.05rem' });
export const chatEmptyHistory = style({ padding: '1rem 0', color: '#64828c', fontSize: '1.25rem', lineHeight: 1.5 });
export const chatHistoryFoot = style({ display: 'flex', alignItems: 'flex-start', gap: '0.7rem', marginTop: 'auto', paddingTop: '1.6rem', borderTop: '0.1rem solid rgba(255,255,255,.09)', color: '#64828c', fontSize: '1.1rem', lineHeight: 1.4 });
export const chatMain = style({ display: 'flex', flexDirection: 'column', minWidth: '0rem', minHeight: '0rem', overflow: 'hidden', padding: '2rem 2.4rem 1.6rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.6rem', background: 'rgba(8,30,44,.72)' });
export const chatMainHead = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem', paddingBottom: '1.6rem', borderBottom: '0.1rem solid rgba(255,255,255,.09)' });
export const chatMainTitle = style({ margin: '0.4rem 0 0', overflow: 'hidden', color: '#eaf3f5', fontSize: '2rem', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
export const chatStatus = style({ display: 'flex', alignItems: 'center', gap: '0.6rem', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.05rem' });
export const chatStatusDot = style({ width: '0.6rem', height: '0.6rem', borderRadius: '50%', background: '#1fc8b5', boxShadow: '0 0 0.8rem rgba(31,200,181,.8)' });
export const chatMessages = style({ display: 'flex', flex: 1, flexDirection: 'column', gap: '2rem', overflowY: 'auto', padding: '2.4rem 1.2rem 2.4rem 0' });
export const chatIntro = style({ maxWidth: '54rem', margin: 'auto', textAlign: 'center' });
export const chatIntroIcon = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '4.4rem', height: '4.4rem', margin: '0 auto 1.4rem', border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '1.2rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5' });
export const chatIntroTitle = style({ margin: '0 0 0.8rem', color: '#eaf3f5', fontSize: '2.4rem' });
export const chatIntroText = style({ margin: '0', color: '#9ab1ba', fontSize: '1.4rem', lineHeight: 1.6 });
export const chatSuggestions = style({ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: '0.8rem', marginTop: '2rem' });
export const chatSuggestion = style({ padding: '0.8rem 1rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '99.9rem', background: 'transparent', color: '#9ab1ba', cursor: 'pointer', fontSize: '1.15rem' });
export const chatMessageAssistant = style({ maxWidth: '70rem', color: '#9ab1ba', fontSize: '1.5rem', lineHeight: 1.7 });
export const chatMessageUser = style({ alignSelf: 'flex-end', maxWidth: '70%', color: '#eaf3f5', fontSize: '1.5rem', lineHeight: 1.6 });
export const chatMessageLabel = style({ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.7rem', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.05rem', textTransform: 'uppercase' });
export const chatMessageBody = style({ padding: '1.4rem 1.6rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.2rem', background: '#0f2434' });
export const chatMessageUserBody = style([chatMessageBody, { borderColor: 'rgba(111,160,255,.28)', background: 'rgba(62,123,250,.12)' }]);
export const chatMessageReferences = style({ display: 'flex', flexWrap: 'wrap', gap: '0.6rem', marginTop: '0.8rem' });
export const chatMessageReferenceLink = style({ color: '#1fc8b5', fontSize: '1.1rem', textDecoration: 'none' });
export const chatInlineCitation = style({ color: '#1fc8b5', fontWeight: 600, textDecoration: 'none' });
export const chatThinking = style({ display: 'flex', alignItems: 'center', gap: '0.7rem', marginLeft: '0.8rem', color: '#9ab1ba', fontSize: '1.25rem' });
export const chatThinkingIcon = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '2.8rem', height: '2.8rem', border: '0.1rem solid rgba(31,200,181,.35)', borderRadius: '50%', background: 'linear-gradient(135deg, rgba(31,200,181,.2), rgba(62,123,250,.2))', color: '#1fc8b5', animation: `${thinkingGlow} 1.8s ease-in-out infinite` });
export const chatThinkingDots = style({ display: 'flex', alignItems: 'center', gap: '0.35rem', marginRight: '0.2rem' });
export const chatThinkingDot = style({ width: '0.45rem', height: '0.45rem', borderRadius: '50%', background: 'linear-gradient(135deg, #1fc8b5, #6fa0ff)', animation: `${thinkingDotPulse} 1.2s ease-in-out infinite` });
globalStyle(`${chatThinkingDot}:nth-child(2)`, { animationDelay: '0.15s' });
globalStyle(`${chatThinkingDot}:nth-child(3)`, { animationDelay: '0.3s' });
export const chatComposer = style({ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) auto', alignItems: 'end', gap: '0.8rem 1rem', padding: '1rem', border: '0.1rem solid rgba(117,166,255,.4)', borderRadius: '1.4rem', background: '#0f2434', boxShadow: '0 1rem 3rem rgba(2,10,16,.35)' });
export const chatComposerInput = style({ flex: 1, minHeight: '4.4rem', maxHeight: '14rem', overflowY: 'hidden', padding: '1rem 0.4rem', border: 0, outline: 0, resize: 'none', background: 'transparent', color: '#eaf3f5', fontFamily: 'inherit', fontSize: '1.45rem', lineHeight: 1.5 });
export const chatComposerButton = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '3.8rem', height: '3.8rem', border: 0, borderRadius: '1rem', background: 'linear-gradient(135deg, #1fc8b5, #3e7bfa)', color: '#04120f', cursor: 'pointer' });
export const chatComposerHint = style({ gridColumn: '1 / -1', padding: '0 0.4rem', color: '#64828c', fontSize: '1rem' });
export const chatReferences = style({ minWidth: '0rem', minHeight: '0rem', overflowY: 'auto', overflowX: 'hidden', padding: '1.6rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.6rem', background: 'rgba(15,36,52,.72)', '@media': { 'screen and (max-width: 100rem)': { display: 'none' } } });
export const chatReferencesHead = style({ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', paddingBottom: '1.6rem', borderBottom: '0.1rem solid rgba(255,255,255,.09)' });
export const chatReferencesTitle = style({ margin: '0.4rem 0 0', color: '#eaf3f5', fontSize: '1.9rem' });
export const chatReferencesCount = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '2.4rem', height: '2.4rem', borderRadius: '50%', background: 'rgba(31,200,181,.1)', color: '#1fc8b5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.1rem' });
export const chatReferenceList = style({ display: 'flex', flexDirection: 'column', gap: '1rem', paddingTop: '1.6rem' });
export const chatReferenceCard = style({ scrollMarginTop: '2rem', minWidth: '0rem', padding: '1.2rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1rem', background: '#0f2434', overflowWrap: 'anywhere' });
export const chatReferenceNumber = style({ display: 'block', marginBottom: '0.5rem', color: '#1fc8b5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.05rem' });
export const chatReferenceLink = style({ color: '#eaf3f5', fontSize: '1.25rem', textDecoration: 'none' });
export const chatReferenceText = style({ margin: '0.7rem 0 0', color: '#64828c', fontSize: '1.15rem', lineHeight: 1.5 });
export const chatReferenceEmpty = style({ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.8rem', padding: '4rem 1rem', color: '#64828c', textAlign: 'center' });
export const chatUnauthenticated = style({ display: 'flex', flexDirection: 'column', alignItems: 'center', maxWidth: '54rem', margin: '10rem auto', padding: '0 2rem', color: '#9ab1ba', textAlign: 'center' });
export const chatWelcomeIcon = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '5rem', height: '5rem', marginBottom: '1.6rem', border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '1.4rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5' });
export const primaryButton = style({ border: 0, borderRadius: '1.2rem', padding: '1rem 1.6rem', background: 'linear-gradient(135deg, #1fc8b5, #3e7bfa)', color: '#04120f', cursor: 'pointer', fontWeight: 700 });
export const secondaryButton = style({ border: '0.1rem solid rgba(255,255,255,.16)', borderRadius: '1rem', padding: '0.8rem 1.2rem', color: '#eaf3f5', background: 'transparent', cursor: 'pointer' });
export const section = style({ padding: '3.6rem 0' });
export const grid = style({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(23rem, 1fr))', gap: '1.4rem' });
export const card = style({ padding: '1.8rem', background: '#0f2434', border: '0.1rem solid rgba(255,255,255,.1)', borderRadius: '1.4rem' });
export const link = style({ color: '#eaf3f5', textDecoration: 'none' });
export const muted = style({ color: '#9ab1ba' });
export const article = style({ maxWidth: '82rem', margin: '4.8rem auto', padding: '2.8rem', background: '#0f2434', border: '0.1rem solid rgba(255,255,255,.1)', borderRadius: '1.6rem', lineHeight: 1.7 });
export const feedback = style({ margin: '1.6rem 0', padding: '1rem 1.2rem', borderRadius: '1rem' });
export const feedbackSuccess = style([feedback, { color: '#c9f7e9', background: 'rgba(31,200,181,.13)', border: '0.1rem solid rgba(31,200,181,.35)' }]);
export const feedbackError = style([feedback, { color: '#ffd7d7', background: 'rgba(235,87,87,.13)', border: '0.1rem solid rgba(235,87,87,.42)' }]);
export const actions = style({ display: 'flex', flexWrap: 'wrap', gap: '1rem', margin: '1.8rem 0' });
export const homeNav = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: '6.8rem', borderBottom: '0.1rem solid rgba(255,255,255,.09)' });
export const homeBrand = style({ display: 'flex', alignItems: 'center', gap: '1rem', color: '#eaf3f5', fontSize: '1.8rem', fontWeight: 600, textDecoration: 'none' });
export const brandMark = style({ width: '2.6rem', height: '2.6rem', flexShrink: 0 });
export const homeNavLinks = style({ display: 'flex', alignItems: 'center', gap: '2.8rem', '@media': { 'screen and (max-width: 86rem)': { display: 'none' } } });
export const homeNavLink = style({ color: '#9ab1ba', fontSize: '1.4rem', fontWeight: 500, textDecoration: 'none' });
export const homeNavRight = style({ display: 'flex', alignItems: 'center', gap: '1.2rem' });
export const graphEdge = style({ fill: 'none', stroke: 'rgba(255,255,255,.16)', strokeWidth: 1, opacity: .55 });
const graphDash = keyframes({ to: { strokeDashoffset: -160 } });
export const graphFlowEdge = style({ fill: 'none', strokeWidth: 1.4, strokeDasharray: '6 10', animation: `${graphDash} 5.5s linear infinite`, opacity: .9 });
export const graphDot = style({ fill: '#1fc8b5' });
export const graphLabel = style({ fill: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.1rem', letterSpacing: '.03em' });
export const pageSectionHead = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '2rem', marginBottom: '2.6rem' });

export const editorNav = style({ position: 'sticky', top: '0rem', zIndex: 10, borderBottom: '0.1rem solid rgba(255,255,255,.09)', background: 'rgba(8,20,32,.88)', backdropFilter: 'blur(1rem)' });
export const editorNavInner = style({ width: 'min(112rem, calc(100% - 3.2rem))', height: '6.4rem', margin: '0 auto', display: 'flex', alignItems: 'center', gap: '2rem' });
export const editorBrand = style({ display: 'flex', alignItems: 'center', gap: '1rem', flexShrink: 0, color: '#eaf3f5', fontSize: '1.7rem', fontWeight: 600, textDecoration: 'none' });
export const editorBrandMark = style({ width: '2.4rem', height: '2.4rem', color: '#1fc8b5', flexShrink: 0 });
export const editorCrumb = style({ flex: 1, overflow: 'hidden', color: '#64828c', fontSize: '1.3rem', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
export const editorCrumbSeparator = style({ margin: '0 0.8rem', opacity: .6 });
export const editorCrumbCurrent = style({ color: '#9ab1ba', fontWeight: 400 });
export const editorNavRight = style({ display: 'flex', alignItems: 'center', gap: '1.2rem', flexShrink: 0 });
export const statusPill = style({ display: 'flex', alignItems: 'center', gap: '0.6rem', padding: '0.5rem 1rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '99.9rem', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.1rem' });
export const statusPillDot = style({ width: '0.6rem', height: '0.6rem', borderRadius: '50%', background: '#1fc8b5' });
export const editorButton = style({ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', padding: '0.9rem 1.6rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1rem', background: 'transparent', color: '#9ab1ba', cursor: 'pointer', fontSize: '1.35rem', fontWeight: 500, textDecoration: 'none' });
export const editorPrimaryButton = style({ padding: '0.9rem 1.6rem', border: 0, borderRadius: '1rem', background: 'linear-gradient(135deg, #1fc8b5, #3e7bfa)', color: '#04120f', cursor: 'pointer', fontSize: '1.35rem', fontWeight: 600 });
export const editorShell = style({ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) 30rem', gap: '4rem', alignItems: 'start', padding: '3.6rem 0 10rem', '@media': { 'screen and (max-width: 90rem)': { gridTemplateColumns: '1fr' } } });
export const editorTitleInput = style({ width: '100%', padding: '0 0 1.4rem', border: 0, outline: 0, background: 'transparent', color: '#eaf3f5', fontFamily: '"Space Grotesk", Inter, sans-serif', fontSize: '3.4rem', fontWeight: 600, letterSpacing: '-.01em', '@media': { 'screen and (max-width: 90rem)': { fontSize: '2.6rem' } } });
export const editorMeta = style({ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: '1.4rem', marginBottom: '2.2rem', paddingBottom: '2rem', borderBottom: '0.1rem solid rgba(255,255,255,.09)', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.2rem' });
export const editorSpace = style({ padding: '0.5rem 1rem', border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '0.7rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5' });
export const editorToolbar = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1.2rem', marginBottom: '1rem' });
export const formatGroup = style({ display: 'flex', alignItems: 'center', gap: '0.2rem' });
export const formatButton = style({ width: '3.2rem', height: '3.2rem', border: '0.1rem solid transparent', borderRadius: '0.7rem', background: 'transparent', color: '#9ab1ba', cursor: 'pointer', fontFamily: '"Space Grotesk", Inter, sans-serif', fontSize: '1.4rem', fontWeight: 600 });
export const formatDivider = style({ width: '0.1rem', height: '1.8rem', margin: '0 0.8rem', background: 'rgba(255,255,255,.09)' });
export const viewSwitch = style({ display: 'flex', padding: '0.2rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '0.9rem', background: '#0c1e2c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.25rem' });
export const viewSwitchButton = style({ padding: '0.6rem 1.2rem', border: 0, borderRadius: '0.7rem', background: 'transparent', color: '#64828c', cursor: 'pointer', fontFamily: 'inherit', fontSize: 'inherit' });
export const viewSwitchActive = style([viewSwitchButton, { background: '#0f2434', color: '#eaf3f5', boxShadow: '0 0.1rem 0.2rem rgba(0,0,0,.15)' }]);
export const editorPanes = style({ display: 'flex', flexDirection: 'column', gap: '1.8rem' });
export const editorPanesWrite = style({});
export const editorPanesPreview = style({});
export const editorPane = style({ overflow: 'hidden', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.4rem', background: '#0f2434' });
export const editorWritePane = style({});
export const editorPreviewPane = style({});
export const editorPaneLabel = style({ padding: '1rem 1.6rem', borderBottom: '0.1rem solid rgba(255,255,255,.09)', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.05rem', letterSpacing: '.06em', textTransform: 'uppercase' });
export const editorTextarea = style({ display: 'block', width: '100%', height: '36rem', padding: '1.6rem', border: 0, outline: 0, resize: 'vertical', background: 'transparent', color: '#eaf3f5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.35rem', lineHeight: 1.7 });
export const editorPreview = style({ maxHeight: '36rem', overflowY: 'auto', padding: '1.6rem 1.8rem', color: '#eaf3f5', fontSize: '1.45rem', lineHeight: 1.7 });
export const editorSidebar = style({ position: 'sticky', top: '8.8rem', display: 'flex', flexDirection: 'column', gap: '2rem', '@media': { 'screen and (max-width: 90rem)': { position: 'static' } } });
export const editorSideCard = style({ padding: '1.6rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.4rem', background: '#0f2434' });
export const editorSideCardTitle = style({ margin: '0 0 1.2rem', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.1rem', fontWeight: 500, letterSpacing: '.06em', textTransform: 'uppercase' });
export const editorField = style({ display: 'flex', flexDirection: 'column', gap: '0.6rem', marginBottom: '1.4rem', color: '#9ab1ba', fontSize: '1.25rem' });
export const editorFieldValue = style({ width: '100%', padding: '0.9rem 1rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '0.8rem', background: '#0c1e2c', color: '#eaf3f5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.2rem', overflowWrap: 'anywhere' });
export const aiHint = style({ display: 'flex', gap: '1rem', padding: '1.2rem', border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '1rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5' });
export const aiHintText = style({ margin: '0rem', color: '#9ab1ba', fontSize: '1.25rem', lineHeight: 1.5 });
export const editorSelect = style({ width: '100%', padding: '0.9rem 1rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '0.8rem', outline: 0, background: '#0c1e2c', color: '#eaf3f5', fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif', fontSize: '1.35rem' });
export const editorCreateSpaceLink = style({ color: '#1fc8b5', fontSize: '1.2rem', textDecoration: 'none' });

export const spacesNav = style({ display: 'flex', alignItems: 'center', height: '6.4rem', gap: '2.4rem', borderBottom: '0.1rem solid rgba(255,255,255,.09)' });
export const spacesBrand = style({ display: 'flex', alignItems: 'center', gap: '1rem', color: '#eaf3f5', fontSize: '1.7rem', fontWeight: 600, textDecoration: 'none' });
export const spacesBrandMark = style({ width: '2.4rem', height: '2.4rem', color: '#1fc8b5' });
export const spacesNavLinks = style({ display: 'flex', alignItems: 'center', alignSelf: 'stretch', gap: '2.8rem', marginLeft: '2rem', '@media': { 'screen and (max-width: 90rem)': { display: 'none' } } });
export const spacesNavLink = style({ display: 'flex', alignItems: 'center', color: '#9ab1ba', fontSize: '1.4rem', fontWeight: 500, textDecoration: 'none' });
export const spacesNavActive = style([spacesNavLink, { position: 'relative', color: '#eaf3f5', selectors: { '&::after': { content: '""', position: 'absolute', right: '0rem', bottom: '0rem', left: '0rem', height: '0.2rem', background: 'linear-gradient(90deg, #1fc8b5, #3e7bfa)' } } }]);
export const spacesNavRight = style({ display: 'flex', alignItems: 'center', gap: '1.2rem', marginLeft: 'auto' });
export const spacesPageHead = style({ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', flexWrap: 'wrap', gap: '2.4rem', padding: '4.4rem 0 2.6rem' });
export const spacesHeadActions = style({ display: 'flex', alignItems: 'center', gap: '1rem' });
export const spacesSearch = style({ display: 'flex', alignItems: 'center', gap: '0.8rem', width: '24rem', height: '4.2rem', padding: '0 1.4rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.2rem', background: '#0f2434', color: '#64828c', '@media': { 'screen and (max-width: 60rem)': { width: '16rem' } } });
export const spacesSearchInput = style({ width: '100%', border: 0, outline: 0, background: 'transparent', color: '#eaf3f5', fontSize: '1.35rem' });
export const spacesPrimaryButton = style({ display: 'inline-flex', alignItems: 'center', gap: '0.8rem', height: '4.2rem', padding: '0 2rem', border: 0, borderRadius: '1.2rem', background: 'linear-gradient(135deg, #1fc8b5, #3e7bfa)', color: '#04120f', cursor: 'pointer', fontSize: '1.35rem', fontWeight: 600, whiteSpace: 'nowrap' });
export const spaceCreateForm = style({ display: 'flex', flexWrap: 'wrap', gap: '1rem', marginBottom: '2rem', padding: '1.6rem', border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '1.4rem', background: 'rgba(31,200,181,.07)' });
export const spacesFormInput = style({ flex: '1 1 22rem', minWidth: '0rem', padding: '1rem 1.2rem', border: '0.1rem solid rgba(255,255,255,.16)', borderRadius: '1rem', outline: 0, background: '#0c1e2c', color: '#eaf3f5', fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif', fontSize: '1.35rem' });
export const spacesIconField = style({ display: 'flex', alignItems: 'center', gap: '0.8rem', color: '#64828c', fontSize: '1.2rem' });
export const spacesFormSelect = style({ padding: '1rem 1.2rem', border: '0.1rem solid rgba(255,255,255,.16)', borderRadius: '1rem', outline: 0, background: '#0c1e2c', color: '#eaf3f5', fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif', fontSize: '1.35rem' });
export const spacesFilterRow = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1.6rem', marginBottom: '3rem', paddingBottom: '1.8rem', borderBottom: '0.1rem solid rgba(255,255,255,.09)' });
export const spacesCount = style({ color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.1rem', letterSpacing: '.08em', textTransform: 'uppercase' });
export const spacesViewToggle = style({ display: 'flex', overflow: 'hidden', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '0.9rem' });
export const spacesViewButton = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '3.4rem', height: '3.2rem', border: 0, borderLeft: '0.1rem solid rgba(255,255,255,.09)', background: '#0f2434', color: '#64828c', cursor: 'pointer' });
export const spacesViewActive = style([spacesViewButton, { color: '#1fc8b5', background: 'rgba(31,200,181,.1)' }]);
export const spacesGrid = style({ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: '1.6rem', '@media': { 'screen and (max-width: 90rem)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' }, 'screen and (max-width: 60rem)': { gridTemplateColumns: '1fr' } } });
export const spacesGridList = style({ display: 'flex', flexDirection: 'column', gap: '0.1rem' });
export const spaceCard = style({ display: 'flex', flexDirection: 'column', padding: '2rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.4rem', background: '#0f2434', color: '#eaf3f5', textDecoration: 'none' });
export const spaceCardTop = style({ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '1.4rem' });
export const spaceIcon = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '3.8rem', height: '3.8rem', borderRadius: '1rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5', fontSize: '1.7rem' });
export const spaceKey = style({ padding: '0.3rem 0.7rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '0.6rem', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.05rem' });
export const spaceFavorite = style({ marginLeft: 'auto', color: '#1fc8b5', filter: 'drop-shadow(0 0 0.5rem rgba(31,200,181,.4))' });
export const spaceCardFoot = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1.2rem', marginTop: 'auto', paddingTop: '1.4rem', borderTop: '0.1rem solid rgba(255,255,255,.09)', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.15rem' });
export const emptySpaces = style({ padding: '4.4rem 0', color: '#9ab1ba' });
export const pageTree = style({ display: 'flex', flexDirection: 'column', gap: '0.4rem' });
export const pageTreeLink = style({ display: 'block', padding: '1rem 1.2rem', borderRadius: '0.8rem', color: '#eaf3f5', textDecoration: 'none' });

export const detailNav = style({ position: 'sticky', top: '0rem', zIndex: 10, borderBottom: '0.1rem solid rgba(255,255,255,.09)', background: 'rgba(8,20,32,.88)', backdropFilter: 'blur(1rem)' });
export const detailNavInner = style({ display: 'flex', alignItems: 'center', width: '100%', height: '6.4rem', gap: '2rem' });
export const detailBrand = style({ display: 'flex', alignItems: 'center', gap: '1rem', flexShrink: 0, color: '#eaf3f5', fontSize: '1.7rem', fontWeight: 600, textDecoration: 'none' });
export const detailBrandMark = style({ width: '2.4rem', height: '2.4rem', color: '#1fc8b5' });
export const detailCrumb = style({ display: 'flex', flex: 1, alignItems: 'center', gap: '0.8rem', marginLeft: '2.2rem', overflow: 'hidden', color: '#64828c', fontSize: '1.3rem', whiteSpace: 'nowrap' });
export const detailCrumbLink = style({ color: '#64828c', textDecoration: 'none' });
export const detailNavRight = style({ display: 'flex', alignItems: 'center', gap: '1.2rem', flexShrink: 0 });
export const detailNavLink = style({ color: '#9ab1ba', fontSize: '1.3rem', textDecoration: 'none' });
export const detailUser = style({ color: '#64828c', fontSize: '1.3rem' });
export const spaceHeader = style({ padding: '3.4rem 0 0' });
export const spaceHeadTop = style({ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1.8rem' });
export const spaceIdentity = style({ display: 'flex', gap: '1.6rem' });
export const spaceTitle = style({ marginTop: 0 });
export const spaceLargeIcon = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '5.8rem', height: '5.8rem', flexShrink: 0, border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '1.6rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5', fontSize: '2.6rem' });
export const spaceKeyBadge = style({ padding: '0.3rem 0.8rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '0.6rem', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.1rem', fontWeight: 400 });
export const spaceActions = style({ display: 'flex', alignItems: 'center', gap: '0.8rem', flexWrap: 'wrap' });
export const detailIconButton = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '3.6rem', height: '3.6rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1rem', background: 'transparent', color: '#9ab1ba', cursor: 'pointer' });
export const detailButton = style({ display: 'flex', alignItems: 'center', gap: '0.7rem', height: '4rem', padding: '0 1.6rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.1rem', background: 'transparent', color: '#9ab1ba', cursor: 'pointer', fontSize: '1.35rem' });
export const detailPrimaryButton = style({ display: 'flex', alignItems: 'center', gap: '0.7rem', height: '4rem', padding: '0 1.6rem', border: 0, borderRadius: '1.1rem', background: 'linear-gradient(135deg, #1fc8b5, #3e7bfa)', color: '#04120f', cursor: 'pointer', fontSize: '1.35rem', fontWeight: 600, textDecoration: 'none' });
export const spaceMetaRow = style({ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: '2.2rem', marginTop: '1.8rem', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.2rem' });
export const contributorStack = style({ display: 'flex', alignItems: 'center' });
export const contributorAvatar = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '2.2rem', height: '2.2rem', marginLeft: '-0.7rem', border: '0.2rem solid #081420', borderRadius: '50%', background: 'linear-gradient(135deg, #3e7bfa, #1fc8b5)', color: '#04120f', fontSize: '0.85rem', fontWeight: 700 });
export const spaceTabs = style({ display: 'flex', gap: '2.6rem', marginTop: '2.6rem', borderBottom: '0.1rem solid rgba(255,255,255,.09)' });
export const spaceTabActive = style({ position: 'relative', padding: '1.2rem 0.2rem', border: 0, background: 'none', color: '#eaf3f5', cursor: 'pointer', fontSize: '1.4rem', fontWeight: 500, selectors: { '&::after': { content: '""', position: 'absolute', right: '0rem', bottom: '-0.1rem', left: '0rem', height: '0.2rem', background: 'linear-gradient(90deg, #1fc8b5, #3e7bfa)' } } });
export const spaceTab = style({ display: 'inline-flex', alignItems: 'center', gap: '0.6rem', padding: '1.2rem 0.2rem', color: '#64828c', fontSize: '1.4rem', textDecoration: 'none' });
export const spaceTabMuted = style({ padding: '1.2rem 0.2rem', color: '#64828c', fontSize: '1.4rem' });
export const spaceTabCount = style({ padding: '0.2rem 0.6rem', borderRadius: '99.9rem', background: 'rgba(255,255,255,.08)', color: '#9ab1ba', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1rem' });
export const spaceBody = style({ display: 'grid', gridTemplateColumns: '27rem minmax(0, 1fr)', gap: '3.6rem', alignItems: 'start', padding: '3rem 0 10rem', '@media': { 'screen and (max-width: 86rem)': { gridTemplateColumns: '1fr' } } });
export const treePanel = style({ position: 'sticky', top: '8.8rem', '@media': { 'screen and (max-width: 86rem)': { position: 'static' } } });
export const treeSearch = style({ display: 'flex', alignItems: 'center', gap: '0.8rem', marginBottom: '1.4rem', padding: '0.8rem 1.1rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1rem', background: '#0f2434', color: '#64828c' });
export const treeSearchInput = style({ width: '100%', border: 0, outline: 0, background: 'transparent', color: '#eaf3f5', fontSize: '1.3rem' });
export const detailPageTree = style({ color: '#9ab1ba' });
export const treeList = style({ margin: '0rem', padding: '0rem', paddingLeft: '1.4rem', borderLeft: '0.1rem solid rgba(255,255,255,.09)', listStyle: 'none' });
export const treeRow = style({ display: 'flex', alignItems: 'center', gap: '0.6rem', minWidth: '0rem', margin: '0.1rem 0', borderRadius: '0.8rem', fontSize: '1.35rem' });
export const treeTwist = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '1.4rem', height: '2.2rem', flexShrink: 0, padding: '0rem', border: 0, background: 'transparent', color: '#64828c', cursor: 'pointer' });
export const treeTwistHidden = style({ visibility: 'hidden' });
export const contentHead = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1.6rem', marginBottom: '1.6rem' });
export const contentControls = style({ display: 'flex', alignItems: 'center', gap: '1rem' });
export const detailSort = style({ padding: '0.7rem 0.9rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '0.9rem', outline: 0, background: '#0f2434', color: '#9ab1ba', fontSize: '1.25rem' });
export const detailViewToggle = style({ display: 'flex', overflow: 'hidden', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '0.9rem' });
export const detailViewButton = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '3.2rem', height: '3rem', border: 0, borderLeft: '0.1rem solid rgba(255,255,255,.09)', background: '#0f2434', color: '#64828c', cursor: 'pointer' });
export const detailViewActive = style([detailViewButton, { color: '#1fc8b5', background: 'rgba(31,200,181,.1)' }]);
export const pageList = style({ borderTop: '0.1rem solid rgba(255,255,255,.09)' });
export const pageRow = style({ display: 'flex', alignItems: 'center', gap: '1.4rem', padding: '1.3rem 0.8rem', borderBottom: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '0.8rem', textDecoration: 'none' });
export const pageDocumentIcon = style({ color: '#64828c', flexShrink: 0 });
export const pageMain = style({ flex: 1, minWidth: '0rem' });
export const pageTitle = style({ display: 'block', overflow: 'hidden', color: '#eaf3f5', fontSize: '1.4rem', fontWeight: 500, textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
export const pagePath = style({ display: 'block', marginTop: '0.2rem', overflow: 'hidden', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.1rem', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
export const pageAuthor = style({ display: 'flex', alignItems: 'center', gap: '0.7rem', width: '15rem', flexShrink: 0, color: '#9ab1ba', fontSize: '1.25rem', '@media': { 'screen and (max-width: 86rem)': { display: 'none' } } });
export const miniAvatar = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '2.2rem', height: '2.2rem', flexShrink: 0, borderRadius: '50%', background: 'linear-gradient(135deg, #3e7bfa, #1fc8b5)', color: '#04120f', fontSize: '0.9rem', fontWeight: 700 });
export const pageTime = style({ width: '7.6rem', flexShrink: 0, color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.2rem', textAlign: 'right' });
export const treeAdd = style({ display: 'flex', alignItems: 'center', gap: '0.7rem', marginTop: '1rem', padding: '0.8rem', borderRadius: '0.8rem', color: '#64828c', fontSize: '1.25rem', textDecoration: 'none' });
export const recentFiles = style({ marginTop: '4.2rem', padding: '2rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.4rem', background: '#0f2434' });
export const recentFilesHead = style({ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1.6rem', marginBottom: '1.4rem' });
export const recentFilesGrid = style({ display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: '0.1rem', '@media': { 'screen and (max-width: 62rem)': { gridTemplateColumns: '1fr' } } });
export const recentFile = style({ display: 'flex', alignItems: 'center', gap: '1rem', minWidth: '0rem', padding: '1.1rem 0.8rem', borderBottom: '0.1rem solid rgba(255,255,255,.09)', color: '#9ab1ba' });
export const recentFileDetails = style({ minWidth: '0rem', flex: 1 });
export const fileLabels = style({ display: 'flex', alignItems: 'center', flexWrap: 'wrap', justifyContent: 'flex-end', gap: '0.4rem', marginLeft: 'auto' });
export const fileLabel = style({ padding: '0.3rem 0.6rem', border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '0.5rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1rem' });
export const filesTab = style({ padding: '3rem 0 10rem' });
export const filesTabHead = style({ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', flexWrap: 'wrap', gap: '2rem', marginBottom: '2.6rem' });
export const filesTabActions = style({ display: 'flex', alignItems: 'center', gap: '0.8rem' });
export const inlineFileForm = style({ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: '0.8rem' });
export const inlineFileInput = style({ width: '15rem', padding: '0.9rem 1rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '0.9rem', outline: 0, background: '#0f2434', color: '#eaf3f5', fontSize: '1.3rem' });
export const filesTabLayout = style({ display: 'grid', gridTemplateColumns: '24rem minmax(0, 1fr)', gap: '3rem', alignItems: 'start', '@media': { 'screen and (max-width: 76rem)': { gridTemplateColumns: '1fr' } } });
export const fileFolderPanel = style({ position: 'sticky', top: '8.8rem', padding: '1.6rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.4rem', background: '#0f2434', '@media': { 'screen and (max-width: 76rem)': { position: 'static' } } });
export const fileFolderTree = style({ margin: '0rem', padding: '0rem', listStyle: 'none' });
export const fileFolderTreeNested = style({ margin: '0rem', padding: '0 0 0 1.6rem', listStyle: 'none' });
export const fileFolderRow = style({ display: 'flex', alignItems: 'center', gap: '0.8rem', padding: '0.8rem 0.6rem', color: '#9ab1ba', fontSize: '1.3rem' });
export const fileFolderRowCount = style({ marginLeft: 'auto', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.1rem' });
export const fileListing = style({ minWidth: '0rem' });
export const fileListingRows = style({ borderTop: '0.1rem solid rgba(255,255,255,.09)' });
export const fileListingHead = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1.4rem', marginBottom: '1.4rem' });
export const fileUploadForm = style({ display: 'flex', alignItems: 'center', flexWrap: 'wrap', justifyContent: 'flex-end', gap: '0.7rem' });
export const fileUploadInput = style({ display: 'none' });
export const spaceFileRow = style({ display: 'flex', alignItems: 'center', gap: '1.1rem', padding: '1.3rem 0.8rem', borderTop: '0.1rem solid rgba(255,255,255,.09)', color: '#9ab1ba' });
export const spaceFileMain = style({ display: 'flex', flexDirection: 'column', minWidth: '0rem', flex: 1 });
export const fileMeta = style({ marginTop: '0.3rem', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.1rem' });

export const pageViewNav = style({ position: 'sticky', top: '0rem', zIndex: 20, borderBottom: '0.1rem solid rgba(255,255,255,.09)', background: 'rgba(8,20,32,.82)', backdropFilter: 'blur(1rem)' });
export const pageViewNavInner = style({ position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: '6.4rem', gap: '1.6rem' });
export const pageViewBrand = style({ display: 'flex', alignItems: 'center', gap: '1rem', color: '#eaf3f5', fontSize: '1.7rem', fontWeight: 600, textDecoration: 'none' });
export const pageViewBrandMark = style({ width: '2.4rem', height: '2.4rem', color: '#1fc8b5', flexShrink: 0 });
export const pageViewCenterLinks = style({ position: 'absolute', left: '50%', display: 'flex', alignItems: 'center', gap: '2.8rem', transform: 'translateX(-50%)', '@media': { 'screen and (max-width: 70rem)': { display: 'none' } } });
export const pageViewNavRight = style({ display: 'flex', alignItems: 'center', gap: '1rem' });
export const pageViewAvatar = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '3.2rem', height: '3.2rem', borderRadius: '50%', background: 'linear-gradient(135deg, #3e7bfa, #1fc8b5)', color: '#04120f', fontSize: '1.1rem', fontWeight: 700 });
export const appFooter = style({ borderTop: '0.1rem solid rgba(255,255,255,.09)', marginTop: '5rem' });
export const appFooterInner = style({ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1.2rem', padding: '3rem 0', color: '#64828c', fontSize: '1.25rem' });
export const termsPage = style({ maxWidth: '82rem', margin: '4.8rem auto 10rem', padding: '2.8rem', background: '#0f2434', border: '0.1rem solid rgba(255,255,255,.1)', borderRadius: '1.6rem', color: '#9ab1ba', fontSize: '1.55rem', lineHeight: 1.75 });
export const pageAvatarMenu = style({ position: 'relative' });
export const pageAvatarDropdown = style({ position: 'absolute', top: '4.2rem', right: '0rem', zIndex: 40, display: 'flex', flexDirection: 'column', minWidth: '19rem', padding: '1.2rem', border: '0.1rem solid rgba(255,255,255,.12)', borderRadius: '1rem', background: '#0f2434', boxShadow: '0 1.4rem 3rem rgba(0,0,0,.25)' });
export const pageActionBar = style({ position: 'sticky', top: '6.4rem', zIndex: 15, borderBottom: '0.1rem solid rgba(255,255,255,.09)', background: 'rgba(8,20,32,.9)', backdropFilter: 'blur(0.8rem)' });
export const pageActionBarInner = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', minHeight: '5.4rem', gap: '1.6rem' });
export const pageBreadcrumb = style({ display: 'flex', alignItems: 'center', gap: '0.7rem', minWidth: '0rem', overflow: 'hidden', color: '#64828c', fontSize: '1.3rem', whiteSpace: 'nowrap' });
export const pageBreadcrumbLink = style({ overflow: 'hidden', color: '#64828c', textOverflow: 'ellipsis', textDecoration: 'none' });
export const pageBreadcrumbCurrent = style({ overflow: 'hidden', color: '#9ab1ba', textOverflow: 'ellipsis' });
export const pageActionGroup = style({ display: 'flex', alignItems: 'center', gap: '0.8rem', flexShrink: 0 });
export const pageIconButton = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '3.6rem', height: '3.6rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1rem', background: 'transparent', color: '#9ab1ba', cursor: 'pointer' });
export const pageActionButton = style({ display: 'flex', alignItems: 'center', gap: '0.6rem', height: '3.6rem', padding: '0 1.4rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1rem', background: 'transparent', color: '#9ab1ba', cursor: 'pointer', fontSize: '1.3rem', fontWeight: 500, textDecoration: 'none', whiteSpace: 'nowrap' });
export const pageActionPrimary = style([pageActionButton, { border: 0, background: 'linear-gradient(135deg, #1fc8b5, #3e7bfa)', color: '#04120f', fontWeight: 600 }]);
export const pageViewBody = style({ display: 'grid', gridTemplateColumns: '22rem minmax(0, 1fr) 24rem', gap: '3.6rem', alignItems: 'start', padding: '3.2rem 0 10rem', '@media': { 'screen and (max-width: 108rem)': { gridTemplateColumns: '1fr' } } });
export const pageSideNav = style({ position: 'sticky', top: '13rem', minWidth: '0rem', '@media': { 'screen and (max-width: 108rem)': { position: 'static' } } });
export const pageSpaceTag = style({ display: 'flex', alignItems: 'center', gap: '0.8rem', marginBottom: '1.4rem', color: '#9ab1ba', fontSize: '1.25rem', fontWeight: 500 });
export const pageSpaceIcon = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '2.2rem', height: '2.2rem', borderRadius: '0.6rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5', fontSize: '1.2rem' });
export const pageMiniTree = style({ margin: '0rem', padding: '0rem', listStyle: 'none' });
export const pageMiniTreeNested = style({ margin: '0rem', marginLeft: '1.2rem', padding: '0 0 0 1rem', borderLeft: '0.1rem solid rgba(255,255,255,.09)', listStyle: 'none' });
export const pageMiniTreeRow = style({ display: 'block', overflow: 'hidden', padding: '0.6rem 0.8rem', borderRadius: '0.7rem', color: '#64828c', fontSize: '1.3rem', textOverflow: 'ellipsis', textDecoration: 'none', whiteSpace: 'nowrap' });
export const pageMiniTreeCurrent = style([pageMiniTreeRow, { background: 'rgba(31,200,181,.1)', color: '#1fc8b5', fontWeight: 600 }]);
export const pageArticle = style({ minWidth: '0rem' });
export const pageArticleHead = style({ marginBottom: '3rem' });
export const pageSpacePill = style({ display: 'inline-flex', alignItems: 'center', gap: '0.6rem', marginBottom: '1.4rem', padding: '0.4rem 0.9rem', border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '99.9rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.1rem' });
export const pageTitleView = style({ margin: '0 0 1.6rem', color: '#eaf3f5', fontFamily: '"Space Grotesk", Inter, sans-serif', fontSize: 'clamp(2.6rem, 4vw, 3.6rem)', fontWeight: 600, letterSpacing: '-.01em', lineHeight: 1.15 });
export const pageArticleMeta = style({ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: '1.4rem', paddingBottom: '2.2rem', borderBottom: '0.1rem solid rgba(255,255,255,.09)', color: '#64828c', fontSize: '1.3rem' });
export const pageAuthorMeta = style({ display: 'flex', alignItems: 'center', gap: '0.8rem', color: '#9ab1ba' });
export const pageProse = style({ marginTop: '2.8rem', color: '#9ab1ba', fontSize: '1.55rem', lineHeight: 1.75 });
export const pageCallout = style({ display: 'flex', gap: '1.2rem', margin: '2rem 0', padding: '1.4rem 1.6rem', border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '1.2rem', background: 'rgba(31,200,181,.1)', color: '#9ab1ba', fontSize: '1.4rem' });
export const pageRightSide = style({ position: 'sticky', top: '13rem', display: 'flex', flexDirection: 'column', gap: '2rem', '@media': { 'screen and (max-width: 108rem)': { position: 'static', flexDirection: 'row', flexWrap: 'wrap' } } });
export const pageSideCard = style({ padding: '1.6rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.4rem', background: '#0f2434', '@media': { 'screen and (max-width: 108rem)': { flex: 1, minWidth: '22rem' } } });
export const pageSideHeading = style({ margin: '0 0 1.2rem', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.1rem', fontWeight: 500, letterSpacing: '.06em', textTransform: 'uppercase' });
export const pageTocLink = style({ display: 'block', padding: '0.6rem 0 0.6rem 1.2rem', borderLeft: '0.2rem solid rgba(255,255,255,.09)', color: '#64828c', fontSize: '1.3rem', textDecoration: 'none' });
export const pageTocSubLink = style([pageTocLink, { paddingLeft: '2.2rem', fontSize: '1.25rem' }]);
export const pageInfoRow = style({ display: 'flex', justifyContent: 'space-between', gap: '1rem', padding: '0.6rem 0', color: '#64828c', fontSize: '1.25rem' });
export const pageInfoValue = style({ color: '#9ab1ba', fontWeight: 500, textAlign: 'right' });
export const pageContribList = style({ display: 'flex', flexDirection: 'column', gap: '1rem' });
export const pageContribRow = style({ display: 'flex', alignItems: 'center', gap: '0.9rem' });
export const pageContribName = style({ color: '#eaf3f5', fontSize: '1.25rem' });
export const pageContribRole = style({ color: '#64828c', fontSize: '1.1rem' });
export const pageAiCited = style({ padding: '1.6rem', border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '1.4rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5' });
export const pageAiNumber = style({ marginTop: '0.7rem', color: '#1fc8b5', fontFamily: '"Space Grotesk", Inter, sans-serif', fontSize: '2.6rem', fontWeight: 600, lineHeight: 1 });
export const pageAiLabel = style({ marginTop: '0.6rem', color: '#9ab1ba', fontSize: '1.2rem', lineHeight: 1.4 });
export const pageEditForm = style({ marginTop: '2.6rem' });
export const pageEditTitle = style({ width: '100%', marginBottom: '1.4rem', padding: '1rem 0', border: 0, borderBottom: '0.1rem solid rgba(255,255,255,.16)', outline: 0, background: 'transparent', color: '#eaf3f5', fontFamily: '"Space Grotesk", Inter, sans-serif', fontSize: '2.8rem', fontWeight: 600 });
export const pageEditTextarea = style({ display: 'block', width: '100%', minHeight: '48rem', padding: '1.6rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.2rem', outline: 0, resize: 'vertical', background: '#0c1e2c', color: '#eaf3f5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.35rem', lineHeight: 1.7 });
export const pageAttachments = style({ marginTop: '5rem', paddingTop: '2.6rem', borderTop: '0.1rem solid rgba(255,255,255,.09)' });
export const pageAttachment = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1.2rem', padding: '1rem 0', borderBottom: '0.1rem solid rgba(255,255,255,.09)', color: '#9ab1ba', fontSize: '1.3rem' });
export const pageRevisionList = style({ display: 'flex', flexDirection: 'column', gap: '0.8rem' });
export const pageRevision = style({ padding: '1rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1rem', background: '#0f2434', color: '#9ab1ba', fontSize: '1.25rem' });
export const ingestionStatus = style({ display: 'inline-flex', alignItems: 'center', gap: '0.6rem', flexShrink: 0, padding: '0.3rem 0.7rem', borderRadius: '99.9rem', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1rem', textTransform: 'capitalize' });
export const ingestionStatusPending = style({ color: '#9ab1ba', background: 'rgba(154,177,186,.12)' });
export const ingestionStatusProcessing = style({ color: '#6fa0ff', background: 'rgba(62,123,250,.14)' });
export const ingestionStatusReady = style({ color: '#1fc8b5', background: 'rgba(31,200,181,.12)' });
export const ingestionStatusFailed = style({ color: '#ffaaa8', background: 'rgba(235,87,87,.14)' });

globalStyle(`${pageProse} p`, { margin: '0 0 1.6rem' });
globalStyle(`${pageProse} h2`, { margin: '4rem 0 1.4rem', color: '#eaf3f5', fontFamily: '"Space Grotesk", Inter, sans-serif', fontSize: '2.1rem', fontWeight: 600, scrollMarginTop: 130 });
globalStyle(`${pageProse} h3`, { margin: '2.8rem 0 1rem', color: '#eaf3f5', fontFamily: '"Space Grotesk", Inter, sans-serif', fontSize: '1.65rem', fontWeight: 600, scrollMarginTop: 130 });
globalStyle(`${pageProse} strong`, { color: '#eaf3f5', fontWeight: 600 });
globalStyle(`${pageProse} code`, { padding: '0.2rem 0.6rem', borderRadius: '0.5rem', background: '#0a1826', color: '#1fc8b5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.3rem' });
globalStyle(`${pageProse} ul, ${pageProse} ol`, { margin: '0 0 1.6rem', paddingLeft: '2.2rem' });
globalStyle(`${pageProse} li`, { marginBottom: '0.6rem' });
globalStyle(`${pageProse} li::marker`, { color: '#1fc8b5' });
globalStyle(`${pageProse} pre`, { margin: '2rem 0', padding: '1.6rem', overflowX: 'auto', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1.2rem', background: '#0a1826' });
globalStyle(`${pageProse} pre code`, { padding: '0rem', background: 'none', color: '#eaf3f5' });
globalStyle(`${pageMiniTreeRow}:hover, ${pageTocLink}:hover, ${pageTocSubLink}:hover`, { color: '#eaf3f5' });

globalStyle('*', { boxSizing: 'border-box' });
globalStyle('html', { fontSize: '62.5%' });
globalStyle('html, body', { margin: '0rem', minHeight: '100%', fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif', WebkitFontSmoothing: 'antialiased' });
globalStyle('html', { scrollbarColor: '#1f8f8b #0a1826', scrollbarWidth: 'thin' });
globalStyle('*::-webkit-scrollbar', { width: '0.9rem', height: '0.9rem' });
globalStyle('*::-webkit-scrollbar-track', { background: '#0a1826' });
globalStyle('*::-webkit-scrollbar-thumb', { border: '0.2rem solid #0a1826', borderRadius: '99.9rem', background: 'linear-gradient(180deg, #1fc8b5, #3e7bfa)' });
globalStyle('*::-webkit-scrollbar-thumb:hover', { background: 'linear-gradient(180deg, #6fa0ff, #1fc8b5)' });
globalStyle('h1, h2, h3, .display', { fontFamily: '"Space Grotesk", Inter, sans-serif', letterSpacing: '-.01em' });
globalStyle('a:hover', { color: '#1fc8b5' });
globalStyle(`${appFooter} a`, { color: '#64828c', textDecoration: 'none' });
globalStyle(`${appFooter} a:hover`, { color: '#eaf3f5' });
globalStyle(`${termsPage} h1`, { margin: '1.6rem 0 0.8rem', color: '#eaf3f5', fontSize: '3.6rem', lineHeight: 1.15 });
globalStyle(`${termsPage} h2`, { margin: '3.2rem 0 1rem', color: '#eaf3f5', fontSize: '2rem', lineHeight: 1.25 });
globalStyle(`${termsPage} p`, { margin: '0 0 1.6rem' });
globalStyle('button:focus-visible, input:focus-visible', { outline: '0rem solid #1fc8b5', outlineOffset: 2 });
globalStyle('button:disabled', { cursor: 'not-allowed', opacity: .6 });
globalStyle(`body:has(${chatPage})`, { overflow: 'hidden' });
globalStyle(`${appShell}:has(${chatPage}) > ${appFooter}`, { display: 'none' });
globalStyle(`${homeConsoleInput}::placeholder`, { color: '#9ab1ba', opacity: 1 });
globalStyle(`${chatHistorySearchInput}::placeholder, ${chatComposerInput}::placeholder`, { color: '#64828c', opacity: 1 });
globalStyle(`${chatConversation}:hover, ${chatConversationActive}:hover`, { borderColor: 'rgba(31,200,181,.25)', background: 'rgba(31,200,181,.08)' });
globalStyle(`${chatConversationRow}:hover ${chatConversationDelete}, ${chatConversationDelete}:focus-visible`, { opacity: 1 });
globalStyle(`${chatConversationDelete}:hover`, { background: 'rgba(255,100,120,.12)', color: '#ff8798' });
globalStyle(`${chatSuggestion}:hover`, { borderColor: 'rgba(31,200,181,.3)', color: '#eaf3f5' });
globalStyle(`${chatMessageBody} p`, { margin: '0 0 1rem' });
globalStyle(`${chatMessageBody} p:last-child`, { marginBottom: '0rem' });
globalStyle(`${chatComposerButton}:disabled`, { cursor: 'not-allowed', opacity: .45 });
globalStyle(`${chatReferenceLink}:hover, ${chatMessageReferenceLink}:hover, ${chatInlineCitation}:hover`, { color: '#6fa0ff' });
globalStyle(`${editorTitleInput}::placeholder, ${editorTextarea}::placeholder`, { color: '#64828c', opacity: 1 });
globalStyle(`${formatButton}:hover`, { borderColor: 'rgba(255,255,255,.09)', background: 'rgba(20,48,68,.53)', color: '#eaf3f5' });
globalStyle(`${editorButton}:hover`, { borderColor: 'rgba(255,255,255,.16)', background: 'rgba(20,48,68,.53)', color: '#eaf3f5' });
globalStyle(`${editorPreview} p`, { margin: '0 0 1.2rem', color: '#9ab1ba' });
globalStyle(`${editorPreview} h1`, { margin: '0 0 1rem', fontSize: '2.2rem' });
globalStyle(`${editorPreview} h2`, { margin: '2.2rem 0 0.8rem', fontSize: '1.7rem' });
globalStyle(`${editorPreview} blockquote`, { margin: '0 0 1.4rem', padding: '0.4rem 1.4rem', borderLeft: '0.3rem solid #1fc8b5', color: '#9ab1ba', fontStyle: 'italic' });
globalStyle(`${editorPreview} code`, { padding: '0.2rem 0.6rem', borderRadius: '0.5rem', background: '#0a1826', color: '#1fc8b5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.25rem' });
globalStyle(`${editorPreview} pre`, { margin: '0 0 1.4rem', padding: '1.2rem 1.4rem', overflowX: 'auto', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1rem', background: '#0a1826' });
globalStyle(`${editorPreview} pre code`, { padding: '0rem', background: 'none', color: '#eaf3f5' });
globalStyle(`${editorPreview} ul`, { margin: '0 0 1.2rem', paddingLeft: '2rem', color: '#9ab1ba' });
globalStyle(`${editorPreview} li`, { marginBottom: '0.4rem' });
globalStyle(`${editorPanesWrite} > ${editorPreviewPane}`, { display: 'none' });
globalStyle(`${editorPanesWrite} > ${editorWritePane}`, { gridColumn: '1 / -1' });
globalStyle(`${editorPanesPreview} > ${editorWritePane}`, { display: 'none' });
globalStyle(`${editorPanesPreview} > ${editorPreviewPane}`, { gridColumn: '1 / -1' });
globalStyle(`${spacesSearchInput}::placeholder`, { color: '#64828c', opacity: 1 });
globalStyle(`${spacesFormInput}::placeholder`, { color: '#64828c', opacity: 1 });
globalStyle(`${spaceCard}:hover`, { transform: 'translateY(-0.3rem)', borderColor: 'rgba(31,200,181,.3)', boxShadow: '0 1.4rem 3rem rgba(0,0,0,.12)' });
globalStyle(`${spaceCard} h2`, { margin: '0 0 0.6rem', fontSize: '1.55rem', fontWeight: 600 });
globalStyle(`${spaceCard} p`, { flex: 1, margin: '0 0 1.6rem', color: '#64828c', fontSize: '1.25rem', lineHeight: 1.5 });
globalStyle(`${spacesGridList} ${spaceCard}`, { flexDirection: 'row', alignItems: 'center', gap: '1.6rem', padding: '1.3rem 1.6rem', borderColor: 'transparent', borderBottom: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '1rem' });
globalStyle(`${spacesGridList} ${spaceCardTop}`, { marginBottom: '0rem' });
globalStyle(`${spacesGridList} ${spaceCard} h2`, { margin: '0rem', whiteSpace: 'nowrap' });
globalStyle(`${spacesGridList} ${spaceCard} p`, { margin: '0rem', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
globalStyle(`${spacesGridList} ${spaceCardFoot}`, { flexShrink: 0, marginTop: '0rem', paddingTop: '0rem', borderTop: 0 });
globalStyle(`${pageTreeLink}:hover`, { background: 'rgba(20,48,68,.53)' });
globalStyle(`${treeRow} a`, { display: 'flex', alignItems: 'center', gap: '0.6rem', minWidth: '0rem', overflow: 'hidden', color: '#9ab1ba', textDecoration: 'none' });
globalStyle(`${treeRow} a span`, { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
globalStyle(`${treeRow} a:hover`, { color: '#eaf3f5' });
globalStyle(`${pageRow}:hover`, { background: 'rgba(20,48,68,.53)' });
globalStyle(`${pageViewCenterLinks} a`, { color: '#9ab1ba', fontSize: '1.4rem', fontWeight: 500, textDecoration: 'none' });
globalStyle(`${pageViewCenterLinks} a:hover`, { color: '#eaf3f5' });
globalStyle(`${pageAvatarDropdown} strong`, { color: '#eaf3f5', fontSize: '1.3rem' });
globalStyle(`${pageAvatarDropdown} small`, { marginTop: '0.3rem', overflow: 'hidden', color: '#64828c', fontSize: '1.1rem', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
globalStyle(`${pageAvatarDropdown} form`, { marginTop: '1rem', borderTop: '0.1rem solid rgba(255,255,255,.09)', paddingTop: '0.9rem' });
globalStyle(`${pageAvatarDropdown} button`, { width: '100%', padding: '0.7rem 0', border: 0, background: 'transparent', color: '#9ab1ba', cursor: 'pointer', fontFamily: 'inherit', fontSize: '1.2rem', textAlign: 'left' });
globalStyle(`${pageAvatarDropdown} button:hover`, { color: '#eaf3f5' });
globalStyle(`${ingestionStatus} button`, { padding: '0rem', border: 0, background: 'transparent', color: 'inherit', cursor: 'pointer', font: 'inherit', textDecoration: 'underline' });
globalStyle(`${recentFiles} h2`, { margin: '0rem', color: '#eaf3f5', fontSize: '1.6rem' });
globalStyle(`${recentFiles} p`, { margin: '0.5rem 0 0', color: '#64828c', fontSize: '1.25rem' });
globalStyle(`${recentFilesHead} a`, { color: '#1fc8b5', fontSize: '1.25rem', textDecoration: 'none', whiteSpace: 'nowrap' });
globalStyle(`${recentFile} b, ${spaceFileRow} b`, { overflow: 'hidden', color: '#eaf3f5', fontSize: '1.3rem', fontWeight: 500, textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
globalStyle(`${recentFile} small, ${spaceFileMain} small`, { marginTop: '0.3rem', overflow: 'hidden', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1.05rem', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
globalStyle(`${fileLabels} em`, { padding: '0.3rem 0.6rem', border: '0.1rem solid rgba(31,200,181,.3)', borderRadius: '0.5rem', background: 'rgba(31,200,181,.1)', color: '#1fc8b5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '1rem', fontStyle: 'normal' });
globalStyle(`${filesTab} h2`, { margin: '0rem', color: '#eaf3f5', fontSize: '2.5rem' });
globalStyle(`${filesTab} h3, ${fileFolderPanel} h3`, { margin: '0rem', color: '#eaf3f5', fontSize: '1.5rem' });
globalStyle(`${fileFolderRow}:hover`, { borderRadius: '0.7rem', background: 'rgba(20,48,68,.53)', color: '#eaf3f5' });
globalStyle(`${fileUploadForm} input:not([type="file"]), ${fileUploadForm} select, ${inlineFileForm} input, ${inlineFileForm} select`, { minWidth: '0rem', padding: '0.8rem 0.9rem', border: '0.1rem solid rgba(255,255,255,.09)', borderRadius: '0.8rem', outline: 0, background: '#0c1e2c', color: '#9ab1ba', fontSize: '1.2rem' });
globalStyle(`${fileUploadForm} input[type="file"]`, { position: 'absolute', width: '0.1rem', height: '0.1rem', opacity: 0 });
