import { globalStyle, keyframes, style } from '@vanilla-extract/css';

export const appShell = style({ minHeight: '100vh', background: 'linear-gradient(160deg, #081420, #0c2431)', color: '#eaf3f5' });
export const shell = style({ width: 'min(1120px, calc(100% - 32px))', margin: '0 auto' });
export const nav = style({ height: 72, display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid rgba(255,255,255,.1)' });
export const brand = style({ display: 'flex', alignItems: 'center', gap: 10, fontSize: 20, fontWeight: 700, letterSpacing: '-.03em' });
export const hero = style({ position: 'relative', padding: '84px 0 60px', overflow: 'hidden', textAlign: 'center' });
export const heroContent = style({ position: 'relative', zIndex: 1 });
export const heroGraph = style({ position: 'absolute', inset: '-40px 0 auto', height: 560, display: 'flex', justifyContent: 'center', pointerEvents: 'none', opacity: .9 });
export const heroGraphSvg = style({ width: '100%', maxWidth: 1180, height: '100%' });
export const eyebrow = style({ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 26, padding: '6px 12px', border: '1px solid rgba(31,200,181,.3)', borderRadius: 999, background: 'rgba(31,200,181,.1)', color: '#1fc8b5', fontFamily: '"IBM Plex Mono", monospace', fontSize: 12, letterSpacing: '.08em', textTransform: 'uppercase' });
export const eyebrowDot = style({ width: 6, height: 6, borderRadius: '50%', background: '#1fc8b5', boxShadow: '0 0 8px #1fc8b5' });
export const headline = style({ margin: '0 0 18px', fontSize: 'clamp(34px, 5.4vw, 58px)', fontWeight: 600, lineHeight: 1.06, letterSpacing: '-.01em' });
export const gradient = style({ background: 'linear-gradient(100deg, #1fc8b5 10%, #6fa0ff 90%)', WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent' });
export const subhead = style({ maxWidth: 540, margin: '0 auto 44px', color: '#9ab1ba', fontSize: 17, lineHeight: 1.55 });
export const chatBox = style({ maxWidth: 720, margin: '0 auto', padding: 10, display: 'flex', gap: 10, background: '#0f2434', border: '1px solid rgba(117,166,255,.4)', borderRadius: 18, boxShadow: '0 20px 60px rgba(2,10,16,.55)' });
export const homeConsole = style({ position: 'relative', maxWidth: 680, margin: '0 auto', padding: 8, background: '#0f2434', border: '1px solid rgba(255,255,255,.16)', borderRadius: 22, boxShadow: '0 20px 60px rgba(2,10,16,.55)' });
export const homeConsoleRow = style({ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 8px 10px 18px' });
export const homeConsoleInput = style({ flex: 1, minWidth: 0, border: 0, outline: 0, background: 'transparent', color: '#eaf3f5', fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif', fontSize: '15.5px' });
export const homeSendButton = style({ width: 40, height: 40, border: 0, borderRadius: 12, background: 'linear-gradient(135deg, #1fc8b5, #3e7bfa)', color: '#04120f', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 });
export const chatInput = style({ flex: 1, minWidth: 0, border: 0, outline: 0, padding: '12px 14px', color: 'inherit', background: 'transparent', fontSize: 16 });
export const primaryButton = style({ border: 0, borderRadius: 12, padding: '10px 16px', background: 'linear-gradient(135deg, #1fc8b5, #3e7bfa)', color: '#04120f', cursor: 'pointer', fontWeight: 700 });
export const secondaryButton = style({ border: '1px solid rgba(255,255,255,.16)', borderRadius: 10, padding: '8px 12px', color: '#eaf3f5', background: 'transparent', cursor: 'pointer' });
export const section = style({ padding: '36px 0' });
export const grid = style({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(230px, 1fr))', gap: 14 });
export const card = style({ padding: 18, background: '#0f2434', border: '1px solid rgba(255,255,255,.1)', borderRadius: 14 });
export const link = style({ color: '#eaf3f5', textDecoration: 'none' });
export const muted = style({ color: '#9ab1ba' });
export const article = style({ maxWidth: 820, margin: '48px auto', padding: 28, background: '#0f2434', border: '1px solid rgba(255,255,255,.1)', borderRadius: 16, lineHeight: 1.7 });
export const feedback = style({ margin: '16px 0', padding: '10px 12px', borderRadius: 10 });
export const feedbackSuccess = style([feedback, { color: '#c9f7e9', background: 'rgba(31,200,181,.13)', border: '1px solid rgba(31,200,181,.35)' }]);
export const feedbackError = style([feedback, { color: '#ffd7d7', background: 'rgba(235,87,87,.13)', border: '1px solid rgba(235,87,87,.42)' }]);
export const actions = style({ display: 'flex', flexWrap: 'wrap', gap: 10, margin: '18px 0' });
export const homeNav = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: 68, borderBottom: '1px solid rgba(255,255,255,.09)' });
export const homeBrand = style({ display: 'flex', alignItems: 'center', gap: 10, color: '#eaf3f5', fontSize: 18, fontWeight: 600, textDecoration: 'none' });
export const brandMark = style({ width: 26, height: 26, flexShrink: 0 });
export const homeNavLinks = style({ display: 'flex', alignItems: 'center', gap: 28, '@media': { 'screen and (max-width: 860px)': { display: 'none' } } });
export const homeNavLink = style({ color: '#9ab1ba', fontSize: 14, fontWeight: 500, textDecoration: 'none' });
export const homeNavRight = style({ display: 'flex', alignItems: 'center', gap: 12 });
export const graphEdge = style({ fill: 'none', stroke: 'rgba(255,255,255,.16)', strokeWidth: 1, opacity: .55 });
const graphDash = keyframes({ to: { strokeDashoffset: -160 } });
export const graphFlowEdge = style({ fill: 'none', strokeWidth: 1.4, strokeDasharray: '6 10', animation: `${graphDash} 5.5s linear infinite`, opacity: .9 });
export const graphDot = style({ fill: '#1fc8b5' });
export const graphLabel = style({ fill: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: 11, letterSpacing: '.03em' });
export const pageSectionHead = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 20, marginBottom: 26 });

export const editorNav = style({ position: 'sticky', top: 0, zIndex: 10, borderBottom: '1px solid rgba(255,255,255,.09)', background: 'rgba(8,20,32,.88)', backdropFilter: 'blur(10px)' });
export const editorNavInner = style({ width: 'min(1120px, calc(100% - 32px))', height: 64, margin: '0 auto', display: 'flex', alignItems: 'center', gap: 20 });
export const editorBrand = style({ display: 'flex', alignItems: 'center', gap: 10, flexShrink: 0, color: '#eaf3f5', fontSize: 17, fontWeight: 600, textDecoration: 'none' });
export const editorBrandMark = style({ width: 24, height: 24, color: '#1fc8b5', flexShrink: 0 });
export const editorCrumb = style({ flex: 1, overflow: 'hidden', color: '#64828c', fontSize: 13, textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
export const editorCrumbSeparator = style({ margin: '0 8px', opacity: .6 });
export const editorCrumbCurrent = style({ color: '#9ab1ba', fontWeight: 400 });
export const editorNavRight = style({ display: 'flex', alignItems: 'center', gap: 12, flexShrink: 0 });
export const statusPill = style({ display: 'flex', alignItems: 'center', gap: 6, padding: '5px 10px', border: '1px solid rgba(255,255,255,.09)', borderRadius: 999, color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: 11 });
export const statusPillDot = style({ width: 6, height: 6, borderRadius: '50%', background: '#1fc8b5' });
export const editorButton = style({ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', padding: '9px 16px', border: '1px solid rgba(255,255,255,.09)', borderRadius: 10, background: 'transparent', color: '#9ab1ba', cursor: 'pointer', fontSize: '13.5px', fontWeight: 500, textDecoration: 'none' });
export const editorPrimaryButton = style({ padding: '9px 16px', border: 0, borderRadius: 10, background: 'linear-gradient(135deg, #1fc8b5, #3e7bfa)', color: '#04120f', cursor: 'pointer', fontSize: '13.5px', fontWeight: 600 });
export const editorShell = style({ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) 300px', gap: 40, alignItems: 'start', padding: '36px 0 100px', '@media': { 'screen and (max-width: 900px)': { gridTemplateColumns: '1fr' } } });
export const editorTitleInput = style({ width: '100%', padding: '0 0 14px', border: 0, outline: 0, background: 'transparent', color: '#eaf3f5', fontFamily: '"Space Grotesk", Inter, sans-serif', fontSize: 34, fontWeight: 600, letterSpacing: '-.01em', '@media': { 'screen and (max-width: 900px)': { fontSize: 26 } } });
export const editorMeta = style({ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 14, marginBottom: 22, paddingBottom: 20, borderBottom: '1px solid rgba(255,255,255,.09)', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: 12 });
export const editorSpace = style({ padding: '5px 10px', border: '1px solid rgba(31,200,181,.3)', borderRadius: 7, background: 'rgba(31,200,181,.1)', color: '#1fc8b5' });
export const editorToolbar = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 10 });
export const formatGroup = style({ display: 'flex', alignItems: 'center', gap: 2 });
export const formatButton = style({ width: 32, height: 32, border: '1px solid transparent', borderRadius: 7, background: 'transparent', color: '#9ab1ba', cursor: 'pointer', fontFamily: '"Space Grotesk", Inter, sans-serif', fontSize: 14, fontWeight: 600 });
export const formatDivider = style({ width: 1, height: 18, margin: '0 8px', background: 'rgba(255,255,255,.09)' });
export const viewSwitch = style({ display: 'flex', padding: 2, border: '1px solid rgba(255,255,255,.09)', borderRadius: 9, background: '#0c1e2c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '12.5px' });
export const viewSwitchButton = style({ padding: '6px 12px', border: 0, borderRadius: 7, background: 'transparent', color: '#64828c', cursor: 'pointer', fontFamily: 'inherit', fontSize: 'inherit' });
export const viewSwitchActive = style([viewSwitchButton, { background: '#0f2434', color: '#eaf3f5', boxShadow: '0 1px 2px rgba(0,0,0,.15)' }]);
export const editorPanes = style({ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)', gap: 18, minHeight: 480, '@media': { 'screen and (max-width: 900px)': { gridTemplateColumns: '1fr' } } });
export const editorPanesWrite = style({});
export const editorPanesPreview = style({});
export const editorPane = style({ overflow: 'hidden', border: '1px solid rgba(255,255,255,.09)', borderRadius: 14, background: '#0f2434' });
export const editorWritePane = style({});
export const editorPreviewPane = style({});
export const editorPaneLabel = style({ padding: '10px 16px', borderBottom: '1px solid rgba(255,255,255,.09)', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: '10.5px', letterSpacing: '.06em', textTransform: 'uppercase' });
export const editorTextarea = style({ display: 'block', width: '100%', height: 440, padding: 16, border: 0, outline: 0, resize: 'vertical', background: 'transparent', color: '#eaf3f5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '13.5px', lineHeight: 1.7 });
export const editorPreview = style({ maxHeight: 440, overflowY: 'auto', padding: '16px 18px', color: '#eaf3f5', fontSize: '14.5px', lineHeight: 1.7 });
export const editorSidebar = style({ position: 'sticky', top: 88, display: 'flex', flexDirection: 'column', gap: 20, '@media': { 'screen and (max-width: 900px)': { position: 'static' } } });
export const editorSideCard = style({ padding: 16, border: '1px solid rgba(255,255,255,.09)', borderRadius: 14, background: '#0f2434' });
export const editorSideCardTitle = style({ margin: '0 0 12px', color: '#64828c', fontFamily: '"IBM Plex Mono", monospace', fontSize: 11, fontWeight: 500, letterSpacing: '.06em', textTransform: 'uppercase' });
export const editorField = style({ display: 'flex', flexDirection: 'column', gap: 6, marginBottom: 14, color: '#9ab1ba', fontSize: '12.5px' });
export const editorFieldValue = style({ width: '100%', padding: '9px 10px', border: '1px solid rgba(255,255,255,.09)', borderRadius: 8, background: '#0c1e2c', color: '#eaf3f5', fontFamily: '"IBM Plex Mono", monospace', fontSize: 12, overflowWrap: 'anywhere' });
export const aiHint = style({ display: 'flex', gap: 10, padding: 12, border: '1px solid rgba(31,200,181,.3)', borderRadius: 10, background: 'rgba(31,200,181,.1)', color: '#1fc8b5' });
export const aiHintText = style({ margin: 0, color: '#9ab1ba', fontSize: '12.5px', lineHeight: 1.5 });

globalStyle('*', { boxSizing: 'border-box' });
globalStyle('html, body', { margin: 0, minHeight: '100%', fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif', WebkitFontSmoothing: 'antialiased' });
globalStyle('h1, h2, h3, .display', { fontFamily: '"Space Grotesk", Inter, sans-serif', letterSpacing: '-.01em' });
globalStyle('a:hover', { color: '#1fc8b5' });
globalStyle('button:focus-visible, input:focus-visible', { outline: '0px solid #1fc8b5', outlineOffset: 2 });
globalStyle('button:disabled', { cursor: 'not-allowed', opacity: .6 });
globalStyle(`${homeConsoleInput}::placeholder`, { color: '#9ab1ba', opacity: 1 });
globalStyle(`${editorTitleInput}::placeholder, ${editorTextarea}::placeholder`, { color: '#64828c', opacity: 1 });
globalStyle(`${formatButton}:hover`, { borderColor: 'rgba(255,255,255,.09)', background: 'rgba(20,48,68,.53)', color: '#eaf3f5' });
globalStyle(`${editorButton}:hover`, { borderColor: 'rgba(255,255,255,.16)', background: 'rgba(20,48,68,.53)', color: '#eaf3f5' });
globalStyle(`${editorPreview} p`, { margin: '0 0 12px', color: '#9ab1ba' });
globalStyle(`${editorPreview} h1`, { margin: '0 0 10px', fontSize: 22 });
globalStyle(`${editorPreview} h2`, { margin: '22px 0 8px', fontSize: 17 });
globalStyle(`${editorPreview} blockquote`, { margin: '0 0 14px', padding: '4px 14px', borderLeft: '3px solid #1fc8b5', color: '#9ab1ba', fontStyle: 'italic' });
globalStyle(`${editorPreview} code`, { padding: '2px 6px', borderRadius: 5, background: '#0a1826', color: '#1fc8b5', fontFamily: '"IBM Plex Mono", monospace', fontSize: '12.5px' });
globalStyle(`${editorPreview} pre`, { margin: '0 0 14px', padding: '12px 14px', overflowX: 'auto', border: '1px solid rgba(255,255,255,.09)', borderRadius: 10, background: '#0a1826' });
globalStyle(`${editorPreview} pre code`, { padding: 0, background: 'none', color: '#eaf3f5' });
globalStyle(`${editorPreview} ul`, { margin: '0 0 12px', paddingLeft: 20, color: '#9ab1ba' });
globalStyle(`${editorPreview} li`, { marginBottom: 4 });
globalStyle(`${editorPanesWrite} > ${editorPreviewPane}`, { display: 'none' });
globalStyle(`${editorPanesWrite} > ${editorWritePane}`, { gridColumn: '1 / -1' });
globalStyle(`${editorPanesPreview} > ${editorWritePane}`, { display: 'none' });
globalStyle(`${editorPanesPreview} > ${editorPreviewPane}`, { gridColumn: '1 / -1' });
