/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ApiIngestionRouteImport } from './routes/api/ingestion'
import { Route as AuthGoogleRouteImport } from './routes/auth/google'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as WikiSlugRouteImport } from './routes/wiki/$slug'
import { Route as WikiNewRouteImport } from './routes/wiki/new'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestionRoute = ApiIngestionRouteImport.update({
  id: '/api/ingestion',
  path: '/api/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiNewRoute = WikiNewRouteImport.update({
  id: '/wiki/new',
  path: '/wiki/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/api/ingestion': typeof ApiIngestionRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki/new': typeof WikiNewRoute
  '/files/': typeof FilesIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/api/ingestion': typeof ApiIngestionRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki/new': typeof WikiNewRoute
  '/files': typeof FilesIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/api/ingestion': typeof ApiIngestionRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki/new': typeof WikiNewRoute
  '/files/': typeof FilesIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/api/ingestion'
    | '/auth/google'
    | '/auth/logout'
    | '/wiki/$slug'
    | '/wiki/new'
    | '/files/'
    | '/wiki/'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/api/ingestion'
    | '/auth/google'
    | '/auth/logout'
    | '/wiki/$slug'
    | '/wiki/new'
    | '/files'
    | '/wiki'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/api/ingestion'
    | '/auth/google'
    | '/auth/logout'
    | '/wiki/$slug'
    | '/wiki/new'
    | '/files/'
    | '/wiki/'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ApiIngestionRoute: typeof ApiIngestionRoute
  AuthGoogleRoute: typeof AuthGoogleRouteWithChildren
  AuthLogoutRoute: typeof AuthLogoutRoute
  WikiSlugRoute: typeof WikiSlugRoute
  WikiNewRoute: typeof WikiNewRoute
  FilesIndexRoute: typeof FilesIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingestion': {
      id: '/api/ingestion'
      path: '/api/ingestion'
      fullPath: '/api/ingestion'
      preLoaderRoute: typeof ApiIngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/new': {
      id: '/wiki/new'
      path: '/wiki/new'
      fullPath: '/wiki/new'
      preLoaderRoute: typeof WikiNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthGoogleRoute
    }
  }
}

interface AuthGoogleRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const AuthGoogleRouteChildren: AuthGoogleRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

const AuthGoogleRouteWithChildren = AuthGoogleRoute._addFileChildren(
  AuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ApiIngestionRoute: ApiIngestionRoute,
  AuthGoogleRoute: AuthGoogleRouteWithChildren,
  AuthLogoutRoute: AuthLogoutRoute,
  WikiSlugRoute: WikiSlugRoute,
  WikiNewRoute: WikiNewRoute,
  FilesIndexRoute: FilesIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
