/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ApiIngestionRouteImport } from './routes/api/ingestion'
import { Route as AuthGoogleRouteImport } from './routes/auth/google'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as SpacesIndexRouteImport } from './routes/spaces/index'
import { Route as SpacesSlugRouteImport } from './routes/spaces/$slug'
import { Route as SpacesNewRouteImport } from './routes/spaces/new'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as SpacesSpaceSlugRouteImport } from './routes/spaces/space/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestionRoute = ApiIngestionRouteImport.update({
  id: '/api/ingestion',
  path: '/api/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSlugRoute = SpacesSlugRouteImport.update({
  id: '/spaces/$slug',
  path: '/spaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesNewRoute = SpacesNewRouteImport.update({
  id: '/spaces/new',
  path: '/spaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthGoogleRoute,
} as any)
const SpacesSpaceSlugRoute = SpacesSpaceSlugRouteImport.update({
  id: '/spaces/space/$slug',
  path: '/spaces/space/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/api/ingestion': typeof ApiIngestionRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/spaces/new': typeof SpacesNewRoute
  '/spaces/': typeof SpacesIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/spaces/space/$slug': typeof SpacesSpaceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/api/ingestion': typeof ApiIngestionRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/spaces/new': typeof SpacesNewRoute
  '/spaces': typeof SpacesIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/spaces/space/$slug': typeof SpacesSpaceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/api/ingestion': typeof ApiIngestionRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/spaces/new': typeof SpacesNewRoute
  '/spaces/': typeof SpacesIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/spaces/space/$slug': typeof SpacesSpaceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/api/ingestion'
    | '/auth/google'
    | '/auth/logout'
    | '/spaces/$slug'
    | '/spaces/new'
    | '/spaces/'
    | '/auth/google/callback'
    | '/spaces/space/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/api/ingestion'
    | '/auth/google'
    | '/auth/logout'
    | '/spaces/$slug'
    | '/spaces/new'
    | '/spaces'
    | '/auth/google/callback'
    | '/spaces/space/$slug'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/api/ingestion'
    | '/auth/google'
    | '/auth/logout'
    | '/spaces/$slug'
    | '/spaces/new'
    | '/spaces/'
    | '/auth/google/callback'
    | '/spaces/space/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ApiIngestionRoute: typeof ApiIngestionRoute
  AuthGoogleRoute: typeof AuthGoogleRouteWithChildren
  AuthLogoutRoute: typeof AuthLogoutRoute
  SpacesSlugRoute: typeof SpacesSlugRoute
  SpacesNewRoute: typeof SpacesNewRoute
  SpacesIndexRoute: typeof SpacesIndexRoute
  SpacesSpaceSlugRoute: typeof SpacesSpaceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingestion': {
      id: '/api/ingestion'
      path: '/api/ingestion'
      fullPath: '/api/ingestion'
      preLoaderRoute: typeof ApiIngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$slug': {
      id: '/spaces/$slug'
      path: '/spaces/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof SpacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/new': {
      id: '/spaces/new'
      path: '/spaces/new'
      fullPath: '/spaces/new'
      preLoaderRoute: typeof SpacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthGoogleRoute
    }
    '/spaces/space/$slug': {
      id: '/spaces/space/$slug'
      path: '/spaces/space/$slug'
      fullPath: '/spaces/space/$slug'
      preLoaderRoute: typeof SpacesSpaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthGoogleRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const AuthGoogleRouteChildren: AuthGoogleRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

const AuthGoogleRouteWithChildren = AuthGoogleRoute._addFileChildren(
  AuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ApiIngestionRoute: ApiIngestionRoute,
  AuthGoogleRoute: AuthGoogleRouteWithChildren,
  AuthLogoutRoute: AuthLogoutRoute,
  SpacesSlugRoute: SpacesSlugRoute,
  SpacesNewRoute: SpacesNewRoute,
  SpacesIndexRoute: SpacesIndexRoute,
  SpacesSpaceSlugRoute: SpacesSpaceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
